# 自动生成的书签配置文件
# 若要更新，请将新的书签HTML文件放入bookmarks/目录
# 此文件使用模块化配置格式，位于config/user/pages/目录下

title: 我的书签
subtitle: 从浏览器导入的书签收藏
categories:
  - name: 论坛
    icon: fas fa-folder
    path:
      - 论坛
    subcategories:
      - name: 新增資料夾
        icon: fas fa-folder
        path:
          - 论坛
          - 新增資料夾
        sites:
          - name: INUX DO CDK
            url: https://cdk.linux.do/
            icon: fas fa-link
            description: ''
          - name: 飞牛
            url: https://club.fnnas.com/
            icon: fas fa-link
            description: ''
          - name: 卡饭网_计算机安全_杀毒软件交流中心 - 互助分享 - 大气谦和!
            url: https://bbs.kafan.cn/portal.php
            icon: fas fa-link
            description: ''
          - name: 小众软件官方论坛 - 小众软件
            url: https://meta.appinn.net/
            icon: fas fa-link
            description: ''
    sites:
      - name: LINUX DO
        url: https://linux.do/
        icon: fas fa-link
        description: ''
      - name: IDC Flare - 域名、主机等信息集散地
        url: https://idcflare.com/
        icon: fas fa-link
        description: ''
      - name: CSDN - 专业开发者社区
        url: https://www.csdn.net/
        icon: fas fa-link
        description: ''
      - name: 克隆窝 | 助互联网玩家寻找每一条道路
        url: https://www.uy5.net/
        icon: fas fa-link
        description: ''
      - name: 黑客说 - 技术驱动优质交流
        url: https://hackertalk.net/
        icon: fas fa-link
        description: ''
      - name: 恩山无线论坛
        url: https://www.right.com.cn/FORUM/forum.php
        icon: fas fa-link
        description: ''
      - name: 百度贴吧——全球领先的中文社区
        url: https://tieba.baidu.com/
        icon: fas fa-link
        description: ''
      - name: NodeSeek
        url: https://www.nodeseek.com/
        icon: fas fa-link
        description: ''
      - name: 全球主机交流论坛 - Powered by Discuz!
        url: https://hostloc.com/
        icon: fas fa-link
        description: ''
      - name: 超理论坛
        url: https://chaoli.club/
        icon: fas fa-link
        description: ''
      - name: 油猴中文网 - 油猴脚本分享交流
        url: https://bbs.tampermonkey.net.cn/forum.php
        icon: fas fa-link
        description: ''
      - name: LowEndTalk
        url: https://lowendtalk.com/
        icon: fas fa-link
        description: ''
      - name: '[~]#棱角 ::Edge.Forum*'
        url: https://forum.ywhack.com/index.php
        icon: fas fa-link
        description: ''
      - name: V2EX
        url: https://www.v2ex.com/
        icon: fas fa-link
        description: ''
      - name: Hot Questions - Stack Exchange
        url: https://stackexchange.com/
        icon: fas fa-link
        description: ''
      - name: LetITFly BBS
        url: https://bbs.letitfly.me/
        icon: fas fa-link
        description: ''
      - name: 美卡论坛 - 在美漂泊的中国人的家园
        url: https://www.uscardforum.com/
        icon: fas fa-link
        description: ''
      - name: 電腦領域 HKEPC Hardware - 全港 No.1 PC網站
        url: https://www.hkepc.com/
        icon: fas fa-link
        description: ''
